version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mining_mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    command: "mosquitto -c /mosquitto/config/mosquitto.conf"
    networks:
      - mining_network

  mining_server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: mining_flask_server
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - mosquitto
    networks:
      - mining_network
    restart: unless-stopped

  mining_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: mining_mqtt_client
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - DATA_FILE=/app/data/mining_data.csv
      - SEND_INTERVAL=10
    volumes:
      - ./data:/app/data
    depends_on:
      - mosquitto
      - mining_server
    networks:
      - mining_network
    restart: unless-stopped
    command: ["python", "mqtt_client.py", "--broker", "mosquitto", 
"--interval", "20"]

networks:
  mining_network:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
